Repository xtdb/xtdb, pull requests merged in 2020-10, with the labels that each got.

#1168 Add nippy and byte-array value types
  crux-core/src/crux/codec.clj
  crux-core/src/crux/kv/index_store.clj
  crux-core/src/data_readers.clj
  crux-core/test/crux/codec_test.clj
  crux-test/test/crux/api_test.clj
  crux-test/test/crux/query_test.clj
Labels: index-bump

#1194 Avoid illegal reflective access
  crux-core/src/crux/cache/second_chance/ConcurrentHashMapTableAccess.java
Labels: dev-experience

#1209 `nil` transact times
  crux-core/src/crux/kv/index_store.clj
  crux-core/src/crux/query.clj
  crux-core/test/crux/fork_test.clj
  crux-http-client/src/crux/remote_api_client.clj
  crux-test/test/crux/api_test.clj
Labels: bug
