Repository xtdb/xtdb, pull requests merged in 2020-08, with the labels that each got.

#1011 Data browser edits - #1007
  crux-http-server/project.clj
  crux-http-server/resources/public/scss/all.scss
  crux-http-server/resources/public/scss/table.scss
  crux-http-server/src-cljs/crux/ui/common.cljs
  crux-http-server/src-cljs/crux/ui/events.cljs
  crux-http-server/src-cljs/crux/ui/http.cljs
  crux-http-server/src-cljs/crux/ui/subscriptions.cljs
  crux-http-server/src-cljs/crux/ui/uikit/table.cljs
  crux-http-server/src-cljs/crux/ui/uikit/utils.cljs
  crux-http-server/src-cljs/crux/ui/views.cljs
  crux-http-server/src/crux/http_server.clj
  crux-test/test/crux/ui_routes_test.clj
Labels: console-399

#1019 Fix missing param to `seek-consumer`
  crux-kafka/src/crux/kafka.clj
  crux-test/test/crux/kafka_test.clj
Labels: bug

#1017 Refactoring of http-server, ensure lazy behaviour of `query`.
  crux-http-server/project.clj
  crux-http-server/src-cljs/crux/ui/codemirror.cljs
  crux-http-server/src-cljs/crux/ui/common.cljs
  crux-http-server/src-cljs/crux/ui/events.cljs
  crux-http-server/src-cljs/crux/ui/http.cljs
  crux-http-server/src-cljs/crux/ui/subscriptions.cljs
  crux-http-server/src/crux/http_server.clj
  crux-http-server/src/crux/http_server/entity.clj
  crux-http-server/src/crux/http_server/entity_ref.cljc
  crux-http-server/src/crux/http_server/query.clj
  crux-http-server/src/crux/http_server/status.clj
  crux-http-server/src/crux/http_server/util.clj
  crux-test/test/crux/ui_routes_test.clj
Labels: console-399

#1031 Data browser - Keep tab state
  crux-http-server/src-cljs/crux/ui/events.cljs
  crux-http-server/src-cljs/crux/ui/http.cljs
  crux-http-server/src-cljs/crux/ui/subscriptions.cljs
  crux-http-server/src-cljs/crux/ui/views.cljs
  crux-http-server/src/crux/http_server/entity.clj
Labels: console-399

#1041 Extracting module docs out of 'configuration.adoc'
  docs/reference/modules/ROOT/examples/src/docs/examples.clj
  docs/reference/modules/ROOT/nav.adoc
  docs/reference/modules/ROOT/pages/building.adoc
  docs/reference/modules/ROOT/pages/configuration.adoc
  docs/reference/modules/ROOT/pages/embedded-kafka.adoc
  docs/reference/modules/ROOT/pages/http.adoc
  docs/reference/modules/ROOT/pages/jdbc.adoc
  docs/reference/modules/ROOT/pages/kafka-connect.adoc
  docs/reference/modules/ROOT/pages/kafka.adoc
  docs/reference/modules/ROOT/pages/lmdb.adoc
  docs/reference/modules/ROOT/pages/monitoring.adoc
  docs/reference/modules/ROOT/pages/queries.adoc
  docs/reference/modules/ROOT/pages/rocksdb.adoc
Labels: docs-386

#1044 Nippy 2.15.0 upgrade
  LICENSE-deps.adoc
  crux-bench/project.clj
  crux-core/project.clj
  crux-core/test/crux/codec_test.clj
  crux-http-client/project.clj
  crux-http-server/project.clj
  crux-jdbc/project.clj
  crux-kafka-connect/project.clj
  crux-kafka-embedded/project.clj
  crux-kafka/project.clj
  crux-lmdb/project.clj
  crux-s3/project.clj
  crux-test/project.clj
  examples/soak/project.clj
  project.clj
Labels: blocked, security

#1055 Ensure that ints, shorts, bytes and floats as keys are translated to longs and doubles respectively
  crux-core/src/crux/codec.clj
  crux-core/src/crux/kv_indexer.clj
  crux-test/test/crux/index_version_override_test.clj
  crux-test/test/crux/tx_test.clj
Labels: debate-reqd
