Repository xtdb/xtdb, pull requests merged in 2020-12, with the labels that each got.

#1284 crux.index refactor
  crux-core/src/crux/codec.clj
  crux-core/src/crux/fork.clj
  crux-core/src/crux/index.clj
  crux-core/src/crux/index/IndexStoreIndexState.java
  crux-core/src/crux/index/NAryJoinLayeredVirtualIndexState.java
  crux-core/src/crux/index/NAryWalkState.java
  crux-core/src/crux/index/RelationVirtualIndexState.java
  crux-core/src/crux/index/SortedVirtualIndexState.java
  crux-core/src/crux/index/UnaryJoinIteratorsThunkFnState.java
  crux-core/src/crux/index/UnaryJoinIteratorsThunkState.java
  crux-core/src/crux/kv/index_store.clj
  crux-core/src/crux/query.clj
  crux-core/test/crux/index_test.clj
  crux-rocksdb/src/crux/rocksdb.clj
  crux-test/test/crux/kv_test.clj
Labels: performance

#1290 Intersection performance tweaks
  crux-core/src/crux/ByteUtils.java
  crux-core/src/crux/index.clj
  crux-core/src/crux/index/UnaryJoinIteratorState.java
Labels: performance

#1299 Value Buffer Thread Local Encoding
  crux-core/src/crux/codec.clj
Labels: performance

#1300 Memory slice and alignment fixes
  crux-core/src/crux/memory.clj
Labels: bug

#1302 crux.index tweaks
  crux-core/src/crux/index.clj
Labels: performance

#1266 Deref kafka producer futures, ensure exceptions are thrown.
  crux-kafka/src/crux/kafka.clj
  crux-test/test/crux/kafka_test.clj
Labels: debate-reqd

#1333 Access to cleaner cleanup map needs to be synchronized.
  crux-core/src/crux/io.clj
Labels: bug
