Repository xtdb/xtdb, pull requests merged in 2020-06, with the labels that each got.

#870 Data browser - Entity histories
  crux-http-server/dev.cljs.edn
  crux-http-server/project.clj
  crux-http-server/resources/public/scss/all.scss
  crux-http-server/src-cljs/crux/ui/common.cljs
  crux-http-server/src-cljs/crux/ui/events.cljs
  crux-http-server/src-cljs/crux/ui/http.cljs
  crux-http-server/src-cljs/crux/ui/main.cljs
  crux-http-server/src-cljs/crux/ui/navigation.cljs
  crux-http-server/src-cljs/crux/ui/routes.cljs
  crux-http-server/src-cljs/crux/ui/subscriptions.cljs
  crux-http-server/src-cljs/crux/ui/uikit/table.cljs
  crux-http-server/src-cljs/crux/ui/uikit/utils.cljs
  crux-http-server/src-cljs/crux/ui/views.cljs
  crux-http-server/src/crux/http_server.clj
Labels: console-399

#914 Refactor IndexStore's `open-entity-history` API -> `entity-history`
  crux-core/src/crux/db.clj
  crux-core/src/crux/kv_indexer.clj
  crux-core/src/crux/query.clj
  crux-core/src/crux/tx.clj
  crux-test/test/crux/kv_indexer_test.clj
  crux-test/test/crux/tx_test.clj
Labels: blocked

#937 Run `deploy-commit` in parallel with `build`.
  .circleci/config.yml
Labels: bench

#938 Circleci - Cache Dataset
  .circleci/config.yml
Labels: bench

#941 Data browser - Download CSV/TSV
  crux-http-server/project.clj
  crux-http-server/resources/public/scss/all.scss
  crux-http-server/src-cljs/crux/ui/subscriptions.cljs
  crux-http-server/src-cljs/crux/ui/views.cljs
  crux-http-server/src/crux/http_server.clj
  crux-test/project.clj
  crux-test/test/crux/ui_routes_test.clj
Labels: console-399

#913 Data browser - Raw EDN view
  crux-http-server/resources/public/scss/all.scss
  crux-http-server/src-cljs/crux/ui/events.cljs
  crux-http-server/src-cljs/crux/ui/subscriptions.cljs
  crux-http-server/src-cljs/crux/ui/views.cljs
Labels: console-399

#943 Bench - Edit Default Behaviours
  crux-bench/bin/run-stress.sh
  crux-bench/src/crux/bench.clj
  crux-bench/src/crux/bench/main.clj
Labels: bench

#949 Pred constraint vars bug
  crux-core/src/crux/query.clj
  crux-test/test/crux/query_test.clj
Labels: bug

#950 Further minor changes to tpch stress
  crux-bench/bin/run-stress.sh
  crux-test/src/crux/fixtures/tpch.clj
Labels: bench

#958 Index version check wasn't failing when upgrading to 1.9.x
  crux-core/src/crux/codec.clj
  crux-core/src/crux/kv_indexer.clj
Labels: bug

#970 Add standalone-lmdb to the sorted-maps run in bench.
  crux-bench/src/crux/bench.clj
  crux-bench/src/crux/bench/main.clj
Labels: bench

#899 Data browser - Various styling changes and additions
  crux-http-server/latofonts.css
  crux-http-server/project.clj
  crux-http-server/resources/public/fonts/Lato-Bold.eot
  crux-http-server/resources/public/fonts/Lato-Bold.ttf
  crux-http-server/resources/public/fonts/Lato-Bold.woff
  crux-http-server/resources/public/fonts/Lato-Bold.woff2
  crux-http-server/resources/public/fonts/Lato-BoldItalic.eot
  crux-http-server/resources/public/fonts/Lato-BoldItalic.ttf
  crux-http-server/resources/public/fonts/Lato-BoldItalic.woff
  crux-http-server/resources/public/fonts/Lato-BoldItalic.woff2
  crux-http-server/resources/public/fonts/Lato-Italic.eot
  crux-http-server/resources/public/fonts/Lato-Italic.ttf
  crux-http-server/resources/public/fonts/Lato-Italic.woff
  crux-http-server/resources/public/fonts/Lato-Italic.woff2
  crux-http-server/resources/public/fonts/Lato-Regular.eot
  crux-http-server/resources/public/fonts/Lato-Regular.ttf
  crux-http-server/resources/public/fonts/Lato-Regular.woff
  crux-http-server/resources/public/fonts/Lato-Regular.woff2
  crux-http-server/resources/public/latofonts.css
  crux-http-server/resources/public/scss/all.scss
  crux-http-server/resources/public/scss/codemirror.scss
  crux-http-server/resources/public/scss/table.scss
  crux-http-server/src-cljs/crux/ui/codemirror.cljs
  crux-http-server/src-cljs/crux/ui/common.cljs
  crux-http-server/src-cljs/crux/ui/events.cljs
  crux-http-server/src-cljs/crux/ui/http.cljs
  crux-http-server/src-cljs/crux/ui/main.cljs
  crux-http-server/src-cljs/crux/ui/subscriptions.cljs
  crux-http-server/src-cljs/crux/ui/uikit/table.cljs
  crux-http-server/src-cljs/crux/ui/uikit/utils.cljs
  crux-http-server/src-cljs/crux/ui/views.cljs
  crux-http-server/src/crux/http_server.clj
Labels: console-399

#974 Fix missing files for `crux-sql` setup for `crux-build`.
  crux-build/clj-uberjar/.gitignore
  crux-build/clj-uberjar/crux-sql.edn
  crux-build/mvn-uberjar/.gitignore
  crux-build/mvn-uberjar/crux-sql.edn
  crux-build/mvn-uberjar/crux.edn
  crux-build/sql-deps.edn
Labels: build
