Repository xtdb/xtdb, pull requests merged in 2023-08, with the labels that each got.

#2633 Local Filename caching for S3
  core/src/main/clojure/xtdb/file_list.clj
  modules/s3/README.adoc
  modules/s3/build.gradle.kts
  modules/s3/cloudformation/s3-stack.yml
  modules/s3/src/main/clojure/xtdb/s3.clj
  modules/s3/src/main/clojure/xtdb/s3/file_list.clj
  src/test/clojure/xtdb/object_store_test.clj
  src/test/clojure/xtdb/s3_test.clj
Labels: 2.x

#2656 add ability to merge log tries and live tries in scan, #2575
  core/src/main/clojure/xtdb/indexer/rrrr.clj
  core/src/main/clojure/xtdb/operator/scan.clj
  core/src/main/clojure/xtdb/trie.clj
  core/src/main/clojure/xtdb/vector/writer.clj
  core/src/main/java/xtdb/trie/LeafMerge.java
  src/main/clojure/xtdb/test_util.clj
  src/test/clojure/xtdb/node_test.clj
  src/test/clojure/xtdb/operator/scan_test.clj
Labels: 2.x

#2673 Add metadata to log trie files, #2650
  core/src/main/clojure/xtdb/indexer/live_index.clj
  core/src/main/clojure/xtdb/metadata.clj
  core/src/main/clojure/xtdb/trie.clj
  core/src/main/java/xtdb/vector/IVectorReader.java
  core/src/main/java/xtdb/vector/IndirectVectorReader.java
  core/src/main/java/xtdb/vector/RenamedVectorReader.java
  core/src/main/java/xtdb/vector/ValueVectorReader.java
  src/test/resources/xtdb/indexer-test/can-build-chunk-as-arrow-ipc-file-format/tables/device_info/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-build-chunk-as-arrow-ipc-file-format/tables/device_readings/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-build-chunk-as-arrow-ipc-file-format/tables/xt$txs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-build-live-index/tables/foo/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-build-live-index/tables/hello/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-build-live-index/tables/world/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-build-live-index/tables/xt$txs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-handle-dynamic-cols-in-same-block/tables/xt$txs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-handle-dynamic-cols-in-same-block/tables/xt_docs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-index-sql-insert/tables/table/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/can-index-sql-insert/tables/xt$txs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/multi-block-metadata/tables/xt$txs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/multi-block-metadata/tables/xt_docs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/writes-log-file/tables/xt$txs/chunks/trie-c00.arrow.json
  src/test/resources/xtdb/indexer-test/writes-log-file/tables/xt_docs/chunks/trie-c00.arrow.json
Labels: 2.x

#2688 IID fast path
  core/src/main/clojure/xtdb/operator/scan.clj
  core/src/main/clojure/xtdb/trie.clj
  core/src/main/clojure/xtdb/util.clj
  src/test/clojure/xtdb/operator/scan_test.clj
Labels: 2.x, indexing

#2711 Remove option to retain vectors from ILiveTableTx openWatermark
  core/src/main/clojure/xtdb/indexer/live_index.clj
Labels: 2.x

#2715 Fix LeafMergeQueue for non-consecutive ordinals
  core/src/main/clojure/xtdb/operator/scan.clj
Labels: 2.x

#2721 Not putting tables in the committed state map until the tx actually commits
  core/src/main/clojure/xtdb/indexer.clj
  core/src/main/clojure/xtdb/indexer/live_index.clj
  src/test/clojure/xtdb/indexer/live_index_test.clj
  src/test/clojure/xtdb/indexer/live_table_test.clj
Labels: 2.x

#2731 IID fast path for non sequential in params
  core/src/main/clojure/xtdb/operator/scan.clj
  src/test/clojure/xtdb/operator/scan_test.clj
Labels: 2.x

#2722 Reinstate pushdown blooms
  core/src/main/clojure/xtdb/metadata.clj
  core/src/main/clojure/xtdb/operator/join.clj
  core/src/main/clojure/xtdb/operator/scan.clj
  core/src/main/clojure/xtdb/operator/set.clj
  src/test/clojure/xtdb/operator/scan_test.clj
Labels: 2.x

#2745 Test fixes
  .circleci/config.yml
  modules/azure-blobs/test/xtdb/azure/blobs_test.clj
  modules/google-cloud-storage/test/xtdb/google/cloud_storage_test.clj
Labels: 1.x
