Repository xtdb/xtdb, pull requests merged in 2025-05, with the labels that each got.

#4414 inline JDBC module within API
  api/build.gradle.kts
  api/java.sql.Driver
  api/src/main/clojure/xtdb/next/jdbc.clj
  api/src/main/clojure/xtdb/next/jdbc/impls.clj
  api/src/main/kotlin/xtdb/jdbc/Driver.kt
  build.gradle.kts
  docs/src/content/docs/drivers/clojure.adoc
  docs/src/content/docs/drivers/java.adoc
  docs/src/content/docs/drivers/kotlin.adoc
  jdbc/build.gradle.kts
  modules/datasets/build.gradle.kts
  settings.gradle.kts
Labels: breaking change

#4426 XT JDBC driver also takes care of encoding Clojure-idiomatic values
  api/src/main/clojure/xtdb/next/jdbc.clj
  api/src/main/clojure/xtdb/serde.clj
  api/src/main/kotlin/xtdb/jdbc/XtConnection.kt
  api/src/main/kotlin/xtdb/util/Transit.kt
  modules/kafka-connect/src/main/clojure/xtdb/kafka/connect.clj
  src/test/clojure/xtdb/pgwire_test.clj
  src/test/clojure/xtdb/sql_test.clj
Labels: breaking change

#4433 add `SET datestyle = 'iso8601'`, and XT JDBC driver now round-trips ZDTs in the correct TZ (#4424)
  api/src/main/kotlin/xtdb/jdbc/Driver.kt
  api/src/main/kotlin/xtdb/jdbc/XtConnection.kt
  build.gradle.kts
  core/src/main/clojure/xtdb/types.clj
  gradle/libs.versions.toml
  src/test/clojure/xtdb/pgwire_test.clj
  src/test/kotlin/xtdb/jdbc/XtConnectionTest.kt
Labels: breaking change

#4443 XTQL queries through SQL can optionally specify `?`s so that PGJDBC knows the param count
  core/src/main/antlr/xtdb/antlr/Sql.g4
  core/src/main/clojure/xtdb/sql.clj
  src/test/clojure/xtdb/sql_test.clj
Labels: pgwire, xtql

#4450 Pgwire error-handling revamp
  core/src/main/clojure/xtdb/pgwire.clj
  core/src/main/clojure/xtdb/pgwire/io.clj
  src/test/clojure/xtdb/metrics_test.clj
  src/test/clojure/xtdb/pgwire_protocol_test.clj
  src/test/clojure/xtdb/pgwire_test.clj
Labels: pgwire

#4451 [pgwire] including ex-cause in the detail part of the ErrorResponse
  api/src/main/clojure/xtdb/serde.clj
  core/src/main/clojure/xtdb/pgwire.clj
  core/src/main/clojure/xtdb/pgwire/io.clj
  src/test/clojure/xtdb/pgwire_protocol_test.clj
  src/test/clojure/xtdb/pgwire_test.clj
Labels: pgwire

#4454 Change default explicit `NULL` behaviour for `PORTION OF VALID_TIME` for DML operations
  core/src/main/antlr/xtdb/antlr/Sql.g4
  core/src/main/clojure/xtdb/expression.clj
  core/src/main/clojure/xtdb/sql.clj
  src/test/clojure/xtdb/pgwire_test.clj
  src/test/clojure/xtdb/sql/temporal_test.clj
  src/test/clojure/xtdb/sql_test.clj
  src/test/resources/xtdb/sql/plan_test_expectations/system-time-as-of.edn
  src/test/resources/xtdb/sql/plan_test_expectations/system-time-between-lateraly-derived-table.edn
  src/test/resources/xtdb/sql/plan_test_expectations/system-time-between-subquery.edn
  src/test/resources/xtdb/sql/plan_test_expectations/system-time-from-a-to-b.edn
  src/test/resources/xtdb/sql/plan_test_expectations/test-dynamic-parameters-103-update-app-time.edn
  src/test/resources/xtdb/sql/plan_test_expectations/test-period-predicate-optimisations-4054-contains-with-period-literal.edn
  src/test/resources/xtdb/sql/plan_test_expectations/test-period-predicate-optimisations-4054-infix-overlaps.edn
  src/test/resources/xtdb/sql/plan_test_expectations/test-sql-delete-plan.edn
  src/test/resources/xtdb/sql/plan_test_expectations/test-sql-update-plan.edn
  src/test/resources/xtdb/sql/plan_test_expectations/valid-and-system-time-period-spec-between.edn
  src/test/resources/xtdb/sql/plan_test_expectations/valid-time-period-spec-as-of.edn
  src/test/resources/xtdb/sql/plan_test_expectations/valid-time-period-spec-between.edn
  src/test/resources/xtdb/sql/plan_test_expectations/valid-time-period-spec-from-to.edn
Labels: breaking change

#4458 Defaulting to `start-of-time` for explicit NULL from in VALID_TIME and SYSTEM_TIME filters
  core/src/main/clojure/xtdb/logical_plan.clj
  core/src/main/clojure/xtdb/operator/scan.clj
  src/test/clojure/xtdb/sql/temporal_test.clj
  src/test/clojure/xtdb/xtql/plan_test.clj
Labels: breaking change

#4471 breaking change: xt/execute-tx throws on transaction failure
  api/src/main/clojure/xtdb/api.clj
  api/src/main/kotlin/xtdb/IllegalArgumentException.kt
  api/src/main/kotlin/xtdb/RuntimeException.kt
  docs/src/content/docs/guides/clojure-sql-cookbook.adoc
  src/main/clojure/xtdb/test_util.clj
  src/test/clojure/xtdb/api_test.clj
  src/test/clojure/xtdb/azure_test.clj
  src/test/clojure/xtdb/compactor_test.clj
  src/test/clojure/xtdb/docs/xtql_walkthrough_test.clj
  src/test/clojure/xtdb/indexer/live_index_test.clj
  src/test/clojure/xtdb/indexer_test.clj
  src/test/clojure/xtdb/kafka_test.clj
  src/test/clojure/xtdb/node_test.clj
  src/test/clojure/xtdb/operator/patch_test.clj
  src/test/clojure/xtdb/sql_test.clj
Labels: breaking change

#4486 Sending j.u.Dates as timestamp-tz over pgwire
  api/src/main/kotlin/xtdb/jdbc/XtConnection.kt
  src/test/kotlin/xtdb/jdbc/XtConnectionTest.kt
Labels: breaking change
